CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL
);

ALTER TABLE public.users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE TABLE public.trips (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_date date NOT NULL,
    name character varying(255) NOT NULL,
    notes character varying(2000),
    start_date date NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.trips
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.trips_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE TABLE public.trip_item (
    id bigint NOT NULL,
    cost bigint,
    cost_status character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    date date,
    name character varying(255) NOT NULL,
    notes character varying(2000),
    updated_at timestamp(6) without time zone,
    trip_id bigint NOT NULL,
    map_search_query character varying(500),
    CONSTRAINT trip_item_cost_status_check CHECK (
        cost_status IN ('CONFIRMED', 'ESTIMATED', 'UNKNOWN')
    )
);

ALTER TABLE public.trip_item
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.trip_item_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE TABLE public.activity (
    end_time time(0) without time zone,
    location character varying(255),
    start_time time(0) without time zone,
    id bigint NOT NULL
);

CREATE TABLE public.transportation (
    arrival_date date,
    arrival_location character varying(255),
    arrival_time time(0) without time zone,
    departure_date date,
    departure_location character varying(255),
    departure_time time(0) without time zone,
    transportation_type character varying(255),
    id bigint NOT NULL,
    CONSTRAINT transportation_transportation_type_check CHECK (
        transportation_type IN (
            'FLIGHT',
            'TRAIN',
            'SUBWAY',
            'BUS',
            'TAXI',
            'FERRY',
            'OTHER'
        )
    )
);

CREATE TABLE public.lodging (
    check_in_date date,
    check_out_date date,
    location character varying(255),
    id bigint NOT NULL
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.trip_item
    ADD CONSTRAINT trip_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transportation
    ADD CONSTRAINT transportation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT lodging_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk8wb14dx6ed0bpp3planbay88u
    FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.trip_item
    ADD CONSTRAINT fkg2tjp7b17a3ym803cscwe3wok
    FOREIGN KEY (trip_id) REFERENCES public.trips(id);

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT fkcmrdln9tgy6685q3fa4n1nvph
    FOREIGN KEY (id) REFERENCES public.trip_item(id);

ALTER TABLE ONLY public.transportation
    ADD CONSTRAINT fk43q3ssv5bi5n7m6uto352anop
    FOREIGN KEY (id) REFERENCES public.trip_item(id);

ALTER TABLE ONLY public.lodging
    ADD CONSTRAINT fke67pwvdh3kdjc0udrw1pk5oiw
    FOREIGN KEY (id) REFERENCES public.trip_item(id);
