CREATE TABLE public.trip_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    duration_days integer NOT NULL,
    is_public boolean NOT NULL DEFAULT false,
    name character varying(100) NOT NULL,
    notes character varying(2000),
    public_key character varying(100),
    updated_at timestamp(6) without time zone,
    owner_id bigint,
    CONSTRAINT trip_template_duration_check CHECK (duration_days > 0),
    CONSTRAINT uq_trip_template_public_key UNIQUE (public_key),
    CONSTRAINT fk_trip_template_owner FOREIGN KEY (owner_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX idx_trip_template_owner
    ON public.trip_template(owner_id);

CREATE INDEX idx_trip_template_public
    ON public.trip_template(is_public);

CREATE TABLE public.trip_template_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id bigint NOT NULL,
    item_type character varying(30) NOT NULL,
    name character varying(100) NOT NULL,
    date_offset integer,
    cost bigint,
    cost_status character varying(255) NOT NULL,
    notes character varying(2000),
    map_search_query character varying(500),
    location character varying(255),
    start_time time(0) without time zone,
    end_time time(0) without time zone,
    transportation_type character varying(255),
    departure_location character varying(255),
    arrival_location character varying(255),
    departure_date_offset integer,
    departure_time time(0) without time zone,
    arrival_date_offset integer,
    arrival_time time(0) without time zone,
    check_in_date_offset integer,
    check_out_date_offset integer,
    CONSTRAINT trip_template_item_type_check CHECK (
        item_type IN ('Activity', 'Transportation', 'Lodging')
    ),
    CONSTRAINT trip_template_item_cost_status_check CHECK (
        cost_status IN ('CONFIRMED', 'ESTIMATED', 'UNKNOWN')
    ),
    CONSTRAINT trip_template_item_transportation_type_check CHECK (
        transportation_type IS NULL OR transportation_type IN (
            'FLIGHT', 'TRAIN', 'SUBWAY', 'BUS', 'TAXI', 'FERRY', 'OTHER'
        )
    ),
    CONSTRAINT fk_trip_template_item_template FOREIGN KEY (template_id)
        REFERENCES public.trip_template(id) ON DELETE CASCADE
);

CREATE INDEX idx_trip_template_item_template
    ON public.trip_template_item(template_id);
