CREATE TABLE public.saved_itinerary_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL,
    item_type character varying(30) NOT NULL,
    name character varying(100) NOT NULL,
    cost bigint,
    cost_status character varying(255) NOT NULL,
    notes character varying(2000),
    map_search_query character varying(500),
    location character varying(255),
    start_time time(0) without time zone,
    end_time time(0) without time zone,
    transportation_type character varying(255),
    departure_location character varying(255),
    arrival_location character varying(255),
    departure_time time(0) without time zone,
    arrival_time time(0) without time zone,
    end_date_offset integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT saved_itinerary_item_type_check CHECK (
        item_type IN ('Activity', 'Transportation', 'Lodging')
    ),
    CONSTRAINT saved_itinerary_item_cost_status_check CHECK (
        cost_status IN ('CONFIRMED', 'ESTIMATED', 'UNKNOWN')
    ),
    CONSTRAINT saved_itinerary_item_transportation_type_check CHECK (
        transportation_type IS NULL OR transportation_type IN (
            'FLIGHT', 'TRAIN', 'SUBWAY', 'BUS', 'TAXI', 'FERRY', 'OTHER'
        )
    ),
    CONSTRAINT fk_saved_itinerary_item_owner FOREIGN KEY (owner_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX idx_saved_itinerary_item_owner
    ON public.saved_itinerary_item(owner_id);
